title: segalla.io
author: igorsegallafa
email: igorsegallafa@gmail.com
description: >
  Hi there, I am Igor Segalla and I am a student of Computer Science at UFPR. I blog about gamedev and things related to programming. Born and raised in Brazil, where I am currently living.
show_excerpts: 'true'
paginate: '10'
paginate_path: '/blog/page:num/'
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag
future: true
dash:
  date_format: '%b %-d, %Y'
  disqus:
    shortname: segalla.io
  social_links:
    - url: 'https://github.com/igorsegallafa'
      icon: github-square
      color: green
    - url: 'https://www.linkedin.com/in/igorsegallafa/'
      icon: linkedin
      color: blue
    - url: 'https://www.instagram.com/igor.segalla/'
      icon: instagram
      color: orange
  show_author: true
  animation_speed: 50
theme: jekyll-dash
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - liquid-md5
  - jekyll/tagging
avatar_source: github
github_username: igorsegallafa
