title: segalla.io
author: igorsegallafa
email: igorsegallafa@gmail.com
description: >
  Hi there, I am Igor Segalla and I am a student of Computer Science at UFPR. I blog about gamedev and things related to programming. Born and raised in Brazil, where I am currently living.
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: igorsegalla-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: 'https://github.com/igorsegallafa'
      icon: github-square
      color: green
    - url: 'https://www.linkedin.com/in/igorsegallafa/'
      icon: linkedin
      color: blue
    - url: 'https://www.instagram.com/igor.segalla/'
      icon: instagram
      color: orange

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain
avatar_source: github
github_username: igorsegallafa